name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Makeup example SECRET
      run: echo 'BOT_TOKEN=1445345523:ex_ampleexampleexampleexampleexample' >> SECRET & echo 'BOT_USERNAME=example_bot_username' >> SECRET
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
